[package]
name = "wasm-lib"
version = "0.1.0"
authors = [ "lolfail <39534294+lolfail@users.noreply.github.com>" ]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
